import { DocArticle } from '../types';

export const ciCdArticles: DocArticle[] = [
  {
    slug: 'ci-cd/gitlab',
    title: 'GitLab CI/CD Integration',
    description: 'Connect GitLab repositories, configure .gitlab-ci.yml pipelines, and automatically ingest pipeline test reports.',
    category: 'ci-cd',
    categoryTitle: 'CI / CD & Ingestion',
    order: 1,
    keywords: ['gitlab', 'ci/cd', 'pipeline', 'gitlab-ci.yml', 'job', 'webhook', 'token', 'integration'],
    lastUpdated: '2026-08-31',
    overview: 'The GitLab integration connects your code repository with the TMS, enabling automated result reporting whenever a CI/CD pipeline completes.',
    sections: [
      {
        id: 'gitlab-setup',
        title: 'GitLab Integration Setup',
        content: '1. Navigate to **Automation Hub** -> **GitLab Integration**.\n2. Enter your GitLab Instance URL (e.g. `https://gitlab.com` or self-hosted).\n3. Provide a Project Access Token with `read_api` / `api` scopes.\n4. Enter your GitLab Project ID or Path.\n5. Click **Verify Connection**.',
        callout: {
          type: 'important',
          title: 'Security First',
          content: 'Access tokens are stored securely and used only for fetching pipeline status and test artifacts.',
        },
      },
      {
        id: 'ci-yml-example',
        title: 'Sample .gitlab-ci.yml Configuration',
        codeSnippet: {
          language: 'yaml',
          code: `stages:\n  - test\n\nplaywright_e2e:\n  stage: test\n  image: mcr.microsoft.com/playwright:v1.40.0-focal\n  script:\n    - npm ci\n    - npx playwright test --reporter=junit\n  artifacts:\n    when: always\n    paths:\n      - results.xml\n    reports:\n      junit: results.xml`,
          caption: 'Exporting JUnit XML in GitLab CI',
        },
      },
    ],
    relatedSlugs: [
      'ci-cd/xml-results',
      'ci-cd/result-mapping',
      'test-execution/run-identifiers',
    ],
  },
  {
    slug: 'ci-cd/xml-results',
    title: 'JUnit XML Result Ingestion',
    description: 'Ingest JUnit, Mocha, and Playwright XML test result files via UI upload or webhook endpoints.',
    category: 'ci-cd',
    categoryTitle: 'CI / CD & Ingestion',
    order: 2,
    keywords: ['xml', 'junit', 'results', 'ingestion', 'upload', 'test results', 'xml import'],
    lastUpdated: '2026-08-31',
    overview: 'The XML Result Ingestion engine accepts standard JUnit/XUnit format XML files generated by test runners, parsing execution status, durations, error traces, and system output.',
    sections: [
      {
        id: 'junit-xml-structure',
        title: 'Supported JUnit XML Structure',
        codeSnippet: {
          language: 'xml',
          code: `<?xml version="1.0" encoding="UTF-8"?>\n<testsuites name="Playwright E2E Suite" tests="2" failures="1" time="4.12">\n  <testsuite name="Authentication @S83920194" timestamp="2026-08-31T10:00:00Z" tests="2" failures="1">\n    <testcase name="Valid Login @T10293847" classname="auth.spec.ts" time="1.45" />\n    <testcase name="Password Reset Flow @T10293848" classname="auth.spec.ts" time="2.67">\n      <failure message="Timeout 5000ms exceeded waiting for locator('#reset-confirm')">\n        Error: Timed out waiting for selector #reset-confirm\n          at /specs/auth.spec.ts:42:15\n      </failure>\n    </testcase>\n  </testsuite>\n</testsuites>`,
          caption: 'Standard JUnit XML with @T and @S tags',
        },
      },
    ],
    relatedSlugs: [
      'ci-cd/gitlab',
      'ci-cd/result-mapping',
      'ci-cd/unmatched-results',
    ],
  },
  {
    slug: 'ci-cd/result-mapping',
    title: 'Result Mapping & Deduplication',
    description: 'How XML results are mapped to test cases using @T IDs and duplicate protection.',
    category: 'ci-cd',
    categoryTitle: 'CI / CD & Ingestion',
    order: 3,
    keywords: ['mapping', 'deduplication', 'id matching', 'fallback', 'pipeline id'],
    lastUpdated: '2026-08-31',
    overview: 'The mapping engine matches each `<testcase>` element in the XML file to a test case in the TMS database.',
    sections: [
      {
        id: 'mapping-stages',
        title: 'Mapping Resolution Stages',
        content: '1. **Exact Test ID Match**: Extracts `@T########` from testcase name or classname and links directly.\n2. **Title-Based Fallback**: If no `@T` ID is found, checks for an exact title match within the target suite.\n3. **Unmatched Result**: If neither succeeds, routes test to the Unmatched Results triage queue.',
      },
    ],
    relatedSlugs: [
      'ci-cd/xml-results',
      'ci-cd/unmatched-results',
    ],
  },
  {
    slug: 'ci-cd/unmatched-results',
    title: 'Unmatched Results & Triage',
    description: 'Reviewing and resolving test results from XML files that could not be matched automatically to a test case.',
    category: 'ci-cd',
    categoryTitle: 'CI / CD & Ingestion',
    order: 4,
    keywords: ['unmatched', 'triage', 'missing id', 'mapping queue', 'resolve'],
    lastUpdated: '2026-08-31',
    overview: 'When XML files contain tests written without `@T` identifiers or newly added tests, they appear in the Unmatched Results view for manual review.',
    sections: [
      {
        id: 'triage-actions',
        title: 'Triage Actions',
        content: '- **Map to Existing Case**: Search the repository and associate the XML test with an existing manual test.\n- **Create as New Test Case**: Convert the XML test into a brand new test case in the target suite.\n- **Ignore**: Discard the result if it was a temporary debug test.',
      },
    ],
    relatedSlugs: [
      'ci-cd/result-mapping',
      'automation/test-ids',
    ],
  },
];
